apiVersion: apps/v1
kind: Deployment
metadata:
  name:  odoo-deployment
  labels:
    app:  odoo
spec:
  selector:
    matchLabels:
      app: odoo
  replicas: 1
  template:
    metadata:
      labels:
        app:  odoo
    spec:
      containers:
      - name:  odoo
        image:  odoo:18
        env:
        - name: HOST
          valueFrom:
            configMapKeyRef:
              name: postgres-configmap
              key: database_url
        - name: USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-user-secret
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password-secret
        ports:
        - containerPort:  8069


---
apiVersion: v1
kind: Service
metadata:
  name: odoo-service
spec:
  type: NodePort
  selector:
    app: odoo
  ports:
    - protocol: TCP
      port: 8069
      targetPort: 8069
      nodePort: 30100
